
kind: pipeline
name: Publish to Docker Hub

steps:
- name: Make
  image: python:3.7-alpine3.9
  commands:
  - chmod +x make.py && ./make.py

  when:
    branch:
    - master


# ---------------------------------

- name: latest
  image: plugins/docker
  settings:
    repo: kudato/baseimage
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - latest
      - 3.9

  when:
    branch:
    - master


# ---------------------------------

- name: python-3.7
  image: plugins/docker
  settings:
    repo: kudato/baseimage
    dockerfile: dockerfiles/python-3.7/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - python-3.7
      - python-3.7-alpine3.9
      - python

  when:
    branch:
    - master


# ---------------------------------

- name: python-3.6
  image: plugins/docker
  settings:
    repo: kudato/baseimage
    dockerfile: dockerfiles/python-3.6/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - python-3.6
      - python-3.6-alpine3.9

  when:
    branch:
    - master


# ---------------------------------

- name: php-cli-7.3
  image: plugins/docker
  settings:
    repo: kudato/baseimage
    dockerfile: dockerfiles/php-cli-7.3/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - php-cli-7.3
      - php-cli-7.3-alpine3.9
      - php-cli

  when:
    branch:
    - master


# ---------------------------------

- name: php-fpm-7.3
  image: plugins/docker
  settings:
    repo: kudato/baseimage
    dockerfile: dockerfiles/php-fpm-7.3/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - php-fpm-7.3
      - php-fpm-7.3-alpine3.9
      - php-fpm

  when:
    branch:
    - master


# ---------------------------------

- name: php-cli-7.2
  image: plugins/docker
  settings:
    repo: kudato/baseimage
    dockerfile: dockerfiles/php-cli-7.2/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - php-cli-7.2
      - php-cli-7.2-alpine3.9

  when:
    branch:
    - master


# ---------------------------------

- name: php-fpm-7.2
  image: plugins/docker
  settings:
    repo: kudato/baseimage
    dockerfile: dockerfiles/php-fpm-7.2/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - php-fpm-7.2
      - php-fpm-7.2-alpine3.9

  when:
    branch:
    - master


# ---------------------------------

- name: node-6.17
  image: plugins/docker
  settings:
    repo: kudato/baseimage
    dockerfile: dockerfiles/node-6.17/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - node-6.17
      - node-6.17-alpine3.9

  when:
    branch:
    - master


# ---------------------------------

- name: node-8.16
  image: plugins/docker
  settings:
    repo: kudato/baseimage
    dockerfile: dockerfiles/node-8.16/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - node-8.16
      - node-8.16-alpine3.9

  when:
    branch:
    - master


# ---------------------------------

- name: node-10.15
  image: plugins/docker
  settings:
    repo: kudato/baseimage
    dockerfile: dockerfiles/node-10.15/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - node-10.15
      - node-10.15-alpine3.9
      - node

  when:
    branch:
    - master


# ---------------------------------

- name: node-11.15
  image: plugins/docker
  settings:
    repo: kudato/baseimage
    dockerfile: dockerfiles/node-11.15/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - node-11.15
      - node-11.15-alpine3.9

  when:
    branch:
    - master


# ---------------------------------

- name: node-12.1
  image: plugins/docker
  settings:
    repo: kudato/baseimage
    dockerfile: dockerfiles/node-12.1/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - node-12.1
      - node-12.1-alpine3.9

  when:
    branch:
    - master


# ---------------------------------
